python gradient_communication.py --arch resnet18 
python gradient_communication.py --arch resnet50 
python gradient_communication.py --arch resnet101 
python gradient_communication.py --arch resnet152 
python gradient_communication.py --arch resnet34 
python gradient_communication.py --arch vgg19 
python gradient_communication.py --arch vgg16 
python gradient_communication.py --arch vgg11 
python gradient_communication.py --arch googlenet 
python gradient_communication.py --arch dense121
python gradient_communication.py --arch dense169
python gradient_communication.py --arch dense201
